### ISSUE TITLE
sourceHash value should be calculated

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#101]
v0.0.10

The "vsw publish" produces error if sourceHash is not specified in publish.json.
The correct behavior should be:
- sourceHash is not specified in publish.json
- vsw takes sourceUrl content and calculates the Hash value as documented in https://docs.google.com/document/d/18v73Mt7F-PKBccUV7QecNAl2KJsTOUYynYNzdWI8g2Y/edit
- vsw fills the calculated/formated value to sourceHash for the credential

Here is the error message:root@bf2fc89a268a:/# vsw publish -c workspace/vsw-0-0-10.json 
2021-05-26 17:40:41 vsw.commands.publish INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py schema name: software-certificate
2021-05-26 17:40:41 vsw.commands.publish INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py executing publish, please waiting for response
2021-05-26 17:40:41 vsw.commands.publish INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py holder connection_id: ef679fa1-9df6-49a2-a171-0e765f6033eb
2021-05-26 17:40:44 vsw.commands.publish INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py Created new software-did: DC3H5c7JDLvuckyEq41fUs
2021-05-26 17:40:44 vsw.commands.publish INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py cred_def_id: 7oyYcUVf2DfqqL4h338Rdj:3:CL:3733:default
Traceback (most recent call last):
  File "/usr/local/bin/vsw", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vsw/__main__.py", line 9, in main
    cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/vsw/cli.py", line 36, in dispatch
    return main(args.args)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py", line 52, in main
    issue_credential(data)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py", line 80, in issue_credential
    proposal_response = send_proposal(data)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/publish.py", line 261, in send_proposal
    "value": data["sourceHash"]
KeyError: 'sourceHash'

The publish.json file used is:
{
  "schemaName": "softwareCertificate",
  "schemaVersion": "0.3",
  "schemaID": "UyDtaEFuTySAV9VZDykHkh:2:softwareCertificate:0.3",
  "softwareName": "vsw",
  "softwareVersion": "0.0.10",
  "softwareUrl": "https://files.pythonhosted.org/packages/ee/d3/bf2b994670dc77d29c657ffdf1fc763207502c5b95a308dac7db50c3a050/vsw-0.0.10.tar.gz",
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "sourceDid": "A",
  "sourceUrl": "https://github.com/verifiablesoftware/vsw/archive/refs/tags/v0.0.10.tar.gz",
  "builderToolDidList": "B",
  "dependencyDidList": "C",
  "buildLog": "D",
  "builderDid": "E"
}

**Comment by wenjing** [comment]
Verified fix in 0.0.14
