### ISSUE TITLE
python_daemon missing in 0.0.11

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#104]
pip3 install python_daemon solves it.

root@b855f90bac4a:/# vsw setup -n wallet1 -p
Traceback (most recent call last):
  File "/usr/local/bin/vsw", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vsw/__main__.py", line 9, in main
    cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/vsw/cli.py", line 34, in dispatch
    main = registered_commands[args.command].load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/setup.py", line 11, in <module>
    import daemon
ModuleNotFoundError: No module named 'daemon'
root@b855f90bac4a:/# pip install python_daemon
bash: pip: command not found
root@b855f90bac4a:/# pip3 install python_daemon
Collecting python_daemon
  Downloading https://files.pythonhosted.org/packages/b1/cc/2ab0d910548de45eaaa50d0372387951d9005c356a44c6858db12dc6b2b7/python_daemon-2.3.0-py2.py3-none-any.whl
Collecting lockfile>=0.10 (from python_daemon)
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from python_daemon)
Requirement already satisfied: docutils in /usr/local/lib/python3.6/dist-packages (from python_daemon)
Installing collected packages: lockfile, python-daemon
Successfully installed lockfile-0.12.2 python-daemon-2.3.0
root@b855f90bac4a:/# 
root@b855f90bac4a:/# 
root@b855f90bac4a:/# 
root@b855f90bac4a:/# vsw setup -n wallet1 -p
Please enter wallet key: 
2021-05-27 19:03:54 vsw.commands.setup INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/setup.py seed:9007749433ff4d3c9deeeb6a136693b2
2021-05-27 19:03:54 vsw.commands.setup INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/setup.py genesis_file: /usr/local/lib/python3.6/dist-packages/vsw/conf/genesis.txt
2021-05-27 19:03:54 vsw.commands.setup INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/setup.py seed:9007749433ff4d3c9deeeb6a136693b2

**Comment by wenjing** [comment]
Verified fix in 0.0.14
