### ISSUE TITLE
creddef json.deoder error 

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#127]
version 0.0.28
after the aws container change

Done installation
vsw version 0.0.28
root@d719826c8804:/workspace# vsw setup newwallet wallet1 -k 12345
Created new wallet
Wallet type: indy
Wallet name: wallet1
Created new public DID: 3yhnrPCvBM3Trcc7tjYBjZ
Verkey: 2d8VVmXaeRyteptLzSakyP8t2RcqjV6Wn4QbGPDf4zJM
Ledger configured
root@d719826c8804:/workspace# vsw setup wallet wallet1 -k 12345 -p 8040,8021,8022
success
root@d719826c8804:/workspace# DDID=$(vsw list -w|tr -d '\r\n'|jq '.results[].did')
root@d719826c8804:/workspace# DDID=$(sed -e 's/^"//' -e 's/"$//' <<<"$DDID")
root@d719826c8804:/workspace# echo "Developer's DID is $DDID"
Developer's DID is 3yhnrPCvBM3Trcc7tjYBjZ
root@d719826c8804:/workspace# vsw setup connection
Created connection successfully!
root@d719826c8804:/workspace# vsw list -c
{
    "results": [
        {
            "accept": "auto",
            "alias": "vsw-agent",
            "connection_id": "61b3e480-b7b1-4e91-b7f8-5322888c0603",
            "created_at": "2021-06-23 17:33:08.508501Z",
            "initiator": "external",
            "invitation_key": "47MXujxnrf31SGmGdRLoKKW6TWT7FTT3g4ed7gEbm6ib",
            "invitation_mode": "once",
            "my_did": "8sETJ9zd3JQrvjhVg91c1p",
            "request_id": "5bde46fe-564d-4395-aef3-345ec3ada1c1",
            "routing_state": "none",
            "state": "active",
            "their_did": "CSsEqA1SDgK9rTJ1NoaMH3",
            "their_label": "Repo.Agent",
            "updated_at": "2021-06-23 17:33:09.395803Z"
        }
    ]
}
root@d719826c8804:/workspace# vsw list -w
{
    "results": [
        {
            "did": "3yhnrPCvBM3Trcc7tjYBjZ",
            "public": true,
            "verkey": "2d8VVmXaeRyteptLzSakyP8t2RcqjV6Wn4QbGPDf4zJM"
        },
        {
            "did": "8sETJ9zd3JQrvjhVg91c1p",
            "public": false,
            "verkey": "5HfPi1Bw4x6nMXbCWbS7XQA6vTt7FL2WqXHpUc7jBXBY"
        }
    ]
}
root@d719826c8804:/workspace# vsw setup creddef -s softwareCertificate

Traceback (most recent call last):
  File "/usr/local/bin/vsw", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vsw/__main__.py", line 9, in main
    cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/vsw/cli.py", line 36, in dispatch
    return main(args.args)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/setup.py", line 59, in main
    init.do_credential_definition(args.schema)
  File "/usr/local/lib/python3.6/dist-packages/vsw/commands/init.py", line 72, in do_credential_definition
    credential_definition_res = json.loads(res.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
root@d719826c8804:/workspace#

**Comment by wenjing** [comment]
Retested in a new computer. Also from scratch. Same error.

**Comment by wenjing** [comment]
This was due to failure to launch the tails server. Fixed now.
