### ISSUE TITLE
twine dependency should not be necessary?

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#77]
twine should not be necessary for regular users of vsw, right?
If so, here is a minor issue.

As a new user try to install and run vsw:
% pip3 install vsw
this succeeds.
but then running vsw shows the following error.
%apt-get install twine
easily resolves it.

root@fef49bacde69:/workspace/vsw# vsw
Traceback (most recent call last):
  File "/usr/local/bin/vsw", line 5, in <module>
    from src.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/src/__init__.py", line 35, in <module>
    metadata = importlib_metadata.metadata("twine")
  File "/usr/lib/python3.8/importlib/metadata.py", line 521, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: twine

**Comment by wenjing** [comment]
Resolved in 0.0.4.
